# Generated by Django 5.0.3 on 2024-03-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
