# Generated by Django 5.0.3 on 2024-03-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_review_sentiment_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cleaned_review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
